Update check-banch-parent.yml

diff --git a/.github/workflows/check-banch-parent.yml b/.github/workflows/check-banch-parent.yml
--- a/.github/workflows/check-banch-parent.yml
+++ b/.github/workflows/check-banch-parent.yml
@@ -1,26 +1,41 @@
-name: Accumulate release
+name: Check PR
 
-on: [push]
+on:
+  pull_request:
+    branches:
+      - 'main'
     
 jobs:
-  build:
+  check-parent-branch:
+    name: VERIFY BASE BRANCH ORIGIN
     runs-on: ubuntu-latest
     steps:
     
-      - name: Extract branch name
-        shell: bash
-        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
-        id: extract_branch
-
       - name: Clone git repo
-        run: git clone https://${{ secrets.ACCES_TOKEN }}@github.com/arachna-net/sandbox.git .
+        run: git clone https://${{ secrets.ACTIONS_ACCESS_TOKEN }}@github.com/BRIDGERPAY/cashier-api.git .
         
-      - name: Checkout to branch ${{ steps.extract_branch.outputs.branch }}
-        run: git checkout ${{ steps.extract_branch.outputs.branch }}
+      - name: Checkout to ${{ github.event.pull_request.head.ref }}
+        run: |
+         git fetch
+         echo "Checing out to ${{ github.event.pull_request.base.ref }}"
+         git checkout ${{ github.event.pull_request.base.ref }}
+         echo "Checing out to ${{ github.event.pull_request.head.ref }}"
+         git checkout ${{ github.event.pull_request.head.ref }}
+      - name: Get parent branch for ${{ github.event.pull_request.head.ref }}
+        id: get_parent_branch
+        run: echo "::set-output name=branch::$(git log --oneline | cut -f 1 -d' ' | (while read commit ; do other_branches=$(git branch --contains $commit | egrep -v '^\* '); if [ -n "${other_branches}" ] ; then echo -e "${other_branches}" && break; fi; done;) | xargs)"
+         
 
-      - name: Get parent branch
-        id: get_parent
-        run: git fetch && echo "::set-output name=parent::$(git log --oneline | cut -f 1 -d' ' | (while read commit ; do other_branches=$(git branch --contains $commit | egrep -v '^\* '); if [ -n "${other_branches}" ] ; then echo -e "${other_branches}" && break; fi; done;) | xargs)"
-
-      - name: Check parent branch
-        run: echo "parent branch is ${{ steps.get_parent.outputs.parent }}" && if [ ${{ steps.get_parent.outputs.parent }} = "origin/whitelabel/base" ]; then echo "Is derived from main"; else echo "Is not derived from main" && exit 1; fi;
+      - name: Check parent branch is ${{ github.event.pull_request.base.ref }} for ${{ github.event.pull_request.head.ref }}
+        run: |
+         echo "Parent branch found: ${{ steps.get_parent_branch.outputs.branch }}"
+         if [ ${{ steps.get_parent_branch.outputs.branch }} = ${{ github.event.pull_request.base.ref }} ]; then echo "${{ github.event.pull_request.head.ref }} is derived from ${{ github.event.pull_request.base.ref }}"; else echo "VERIFICATION FAILURE: ${{ github.event.pull_request.head.ref }} is not derived from ${{ github.event.pull_request.base.ref }}. Derived branch is: ${{ steps.get_parent_branch.outputs.branch }}" && exit 1; fi;
+  check-if-compile:
+    name: CHECK COMPILING
+    runs-on: ubuntu-latest
+    needs: [check-parent-branch]
+    steps:
+      - uses: actions/checkout@v3
+      
+      - name: Compile solution
+      - run: echo "build solution"
